[package]
name = "rust-number-spirals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
primal = "0.3.2"
svg = "0.13.1"
